version: 0.2

phases:
 install:
  runtime-versions:
   java: corretto8
  build:
    commands:
      - echo started Build phase
      - mvn clean package
      - aws cloudformation package --debug --template-file /SimpleAPI.yml --output-template-file /template-export.yml
  post_build:
    commands:
      - echo Build completed successfully..
artifacts:
  files:
    - target/hello-world.jar
    - template-export.yml
  discard-paths: yes
